### ISSUE TITLE
Issue when Selecting Folder

### ISSUE THREAD

**Issue by davidevan84** [RedDuckss/CemuManager#13] opened 2017-04-11 23:20 UTC
When it asks me which folder to select for the games. This pops up and it wont proceed forward. Just thought you might like to know. Also I tried moving games to a different directory outside of the Desktop itself. Still throws Java error.

![cemumanagererror](https://cloud.githubusercontent.com/assets/22285162/24934772/4a9fa238-1ee3-11e7-8cda-20d86d7289bd.png)

**Comment by RedDuckss** [comment] 2017-04-11 23:29
Could you provide the structure of your games folder? Also this seems to be related to #14 as both relate to scanning the games folder. A developer has been assigned to #14

**Comment by LrrrAc** [comment] 2017-04-12 01:36
I have the same issue, my folder only contains the folders of the loadline code for each game.

**Comment by davidevan84** [comment] 2017-04-12 01:43
Sorry for the late response. Ya same as what LrrrAc said. It is just a straight Rip of the game. Nothing added from what I can tell.

**Comment by RedDuckss** [comment] 2017-04-12 01:51
Could you provide me the name of the exact game that this is happening with? The folder in the error does not seem to be the name of a real game, it appears to be a random string. I have also checked the line which this is happening on, and it is the part which scans the `code` directory. This puzzles me, as it throws an error stating that the path does not exist, yet in order to even get to that line in the code, it is being verified that the path _does_ exist.

**Comment by RedDuckss** [comment] 2017-04-12 01:57
@LrrrAc does this issue occur for all your games? I cannot seem to reproduce this issue.

**Comment by LrrrAc** [comment] 2017-04-12 02:11
It only happens with New Super Mario Bros. I removed the folder and it works. It never was able to load the cover art with version 1.0 for it either.

**Comment by RedDuckss** [comment] 2017-04-12 02:24
@LrrrAc If you are still using version 0.1.0 (which you mentioned a bug occurring on) please update to 0.1.2 and try again. Many changes were made in version 0.1.2, including a change to how box art was downloaded (which is the bug you mentioned).

@davidevan84 If you are still using version 0.1.0 (which you may) then please update to version 0.1.2, which can be found in the `Releases` section. This will ensure that the error you have matches the corresponding lines in the most recent version, allowing us to properly fix this bug.

**Comment by davidevan84** [comment] 2017-04-12 02:26
I am currently using 0.1.2. Also it happens with multiple games. I've been using an app called Maple Seed to download and update some of my games. Not sure if this adds something I'm not seeing in the folder. Hopefully this helps.

**Comment by RedDuckss** [comment] 2017-04-12 02:28
If you would, please list at least one game with you can confirm this bug happening on. I will download a copy of it to try and replicate the bug, as I cannot replicate it with any of the 3 games I have (Zelda BOTW, Captain Toad, and Mario Kart 8)

**Comment by davidevan84** [comment] 2017-04-12 02:29
Ugh...I took one of the only games I didnt download from Maple Seed and tried doing it by itself and now I get a totally new error. 

![cmerror](https://cloud.githubusercontent.com/assets/22285162/24938614/e88f736e-1efd-11e7-9041-34ea91da551c.png)

**Comment by davidevan84** [comment] 2017-04-12 02:31
Thats weird, Ive tested it with both BOTW and Mario Kart 8 both give me the same error.

**Comment by RedDuckss** [comment] 2017-04-12 02:32
That error seems to be related to another bug previous mentioned here, which I posted a (possible) fix for in the `dev` branch. However I was not able to personally test the fix as I do not have copies of the games mentioned in the other bug report.

**Comment by RedDuckss** [comment] 2017-04-12 02:32
If it is happening with BOTW and Mario Kart, it may very well be Maple Seed then, as I am unable to replicate the error with those games.

**Comment by davidevan84** [comment] 2017-04-12 02:36
Just tried a couple other games that I did not get from Maple Seed. Still giving same First error code.

**Comment by davidevan84** [comment] 2017-04-12 02:36
Paper Mario Splash and Twilight Princess

**Comment by LrrrAc** [comment] 2017-04-12 02:38
I am currently on 1.2, and thats where i get this error with New Super Mario Bros. On version 1.0 it just wouldnt have artwork for that game.

**Comment by davidevan84** [comment] 2017-04-12 02:42
I am going to download .1.0 and see If the errors go away. Thanks for the heads up.

**Comment by RedDuckss** [comment] 2017-04-12 02:51
If the issue does not persist in version 0.1.0 please let me know. Also, if you wouldn't mind please also try the version found in the `dev` branch as I have added several additional checks for the game data downloading. You will either need to build from source or run as dev, either way works as both are the same.

**Comment by davidevan84** [comment] 2017-04-12 03:02
Ya its what LrrrAc stated with 0.1.0. With certain games it just doesn't show the artwork but it doesn't crash.

**Comment by RedDuckss** [comment] 2017-04-12 03:11
The issue with gameart not downloading is fixed in v0.1.2. But it's odd that it doesn't throw any errors in that version. Guess that means I broke something while fixing something? Oh joy 😅 Have you attempted the `dev` branch as per request? It would be helpful to know if the changes made there solved this issue or not, as the changes made were aimed at this issue.

**Comment by davidevan84** [comment] 2017-04-12 03:17
Just a heads up Im not a programmer. So when it says install npm and node. I wasnt sure what thats meaning exactly.

**Comment by RedDuckss** [comment] 2017-04-12 03:19
Node refers to NodeJs. It's just a simple install, and it comes with npm. When it's done you just need to run the `install.bat` file, which will install the dependencies needed for the program, then run `run-dev.bat` which will run an un-compiled (dev) version of CemuManager. It opens the command prompt, which will log any crash data.

**Comment by davidevan84** [comment] 2017-04-12 03:29
ok I see a npm-debug/log...Are you needing this?

**Comment by LrrrAc** [comment] 2017-04-12 03:35
yeah i dont know what npm is either :/

**Comment by LrrrAc** [comment] 2017-04-12 03:36
https://nodejs.org/dist/v6.10.2/node-v6.10.2-x64.msi found it

**Comment by RedDuckss** [comment] 2017-04-12 03:40
`npm-debug/log` refers to npm, not CemuManager. npm comes pre-installed with NodeJs (I am using NodeJs version 7.0.0, version 6.10.2 is outdated). I am currently uploading a compiled build of the dev branch to dropbox to save time.

**Comment by RedDuckss** [comment] 2017-04-12 03:44
https://www.dropbox.com/s/tnxoca1afu6ne4s/CemuManager-win32-ia32.zip?dl=0

Here is a compiled version of the dev branch

**Comment by LrrrAc** [comment] 2017-04-12 03:44
Thank you

**Comment by davidevan84** [comment] 2017-04-12 03:46
Ya Same error here too.

**Comment by davidevan84** [comment] 2017-04-12 03:52
Im headed to bed for the night. I know this is in its early stages. I am sure it will end up being great. Thanks again for doing this.

**Comment by RedDuckss** [comment] 2017-04-12 03:53
Alright, back to square one then. I guess I'll try to build up from v0.1.0 again and see where the issue is happening. However it is difficult for me to track down the cause as I cannot replicate any errors being shown here, even though we are using some of the same games. Also you are making sure that you are selecting the _parent_ folder and not the actual game folder itself, correct?

Fort example, my folder structure is:

```
Games 
│
└─── WiiU
│   │─── Captain Toad Treasure Tracker [AKBP01]
│   │─── MarioKart8
│   └─── The Legend of Zelda Breath of the Wild
```
Where `Captain Toad Treasure Tracker [AKBP01]`, `MarioKart8` and `The Legend of Zelda Breath of the Wild` are the games (containing the `code`, `content` and `meta` folders) and I would select the `WiiU` folder, not any of the actual game folders.

**Comment by RedDuckss** [comment] 2017-04-12 15:46
I think I might have found a possible cause for the bug. I compared the source from v0.1.0 to v0.1.2, checking the areas in question, and there was one change made in how the game folder path. I cannot push any changes at the moment, but I have asked @MrIlliteracy to take a look

**Comment by boonynator** [comment] 2017-04-12 18:54
Hey RedDuckss, I sent you a message regarding the error yesterday on Reddit. The issue occurred to me in version 0.1.0 as well as the newest.

Wii U Games
│ 
└──── Wind Waker HD
└──── The Legend of Zelda Breath of the Wild
└──── Xenoblade Chronicles X
└──── Misc
│            │─── controls (Directory containing cemu .ccc file)
│            │─── BOTW 6.5k + 15k.rar
│            │─── *insert random Wii U game name* .zip file
.....

Meaning that Misc directory does not directly contain any "code", "content" and "meta" folders, but it does in the archives.

*A temporary fix is obviously to get rid of all folders in your game directory, which the error displays and move them somewhere else.*

**Comment by RedDuckss** [comment] 2017-04-13 00:04
https://www.dropbox.com/s/ukhoqzloxqz3o26/CemuManager-win32-ia32%20DEV2.zip?dl=0

Please try this new compiled build everyone. Cross your fingers that this fixes things 😅 I'm having a bit of a hard time fixing this one because I can't replicate the bug in anyway, so I'm making fixes and changes based only on the error messages (which can be cryptic and cut-off, not showing the full error). So bare with me on this one guys 😅

**Comment by davidevan84** [comment] 2017-04-13 00:09
Sorry doesn't fix the issue.

**Comment by RedDuckss** [comment] 2017-04-13 00:17
@davidevan84 Is it still the same exact error message?

**Comment by RedDuckss** [comment] 2017-04-13 00:20
I changed several things in that build, if you would please post a screenshot of the error message so I can which line the error now occurs on. I'm still trying to pinpoint the exact cause of this, so I need to see the error message to find the line.

**Comment by davidevan84** [comment] 2017-04-13 00:23
Depends which game and what directory here are two different Screen Shots.
![error1](https://cloud.githubusercontent.com/assets/22285162/24984802/86f417a0-1fb5-11e7-9aa3-75b3d02d668d.png)

**Comment by davidevan84** [comment] 2017-04-13 00:23
![error2](https://cloud.githubusercontent.com/assets/22285162/24984808/8b3715f6-1fb5-11e7-8a8f-4260ec160308.png)

**Comment by LrrrAc** [comment] 2017-04-13 00:24
![capture](https://cloud.githubusercontent.com/assets/27321984/24984828/017309a2-1fbe-11e7-82a7-5d72072391c6.PNG)
heres my error code with super mario

**Comment by RedDuckss** [comment] 2017-04-13 00:38
Well shit (pardon my french) all those errors are on completely different lines, which means there's 3 issues going on here :L crap. Okay, this narrows things down for me.

@davidevan84 it appears you are having 2 separate issues. The first being that it cannot find the `meta` file of the game. The folder it's looking in seems to be a valid game (Zelda Twilight Princess). Are you able to verify that a `meta.xml` file exists in that directory? Your second issue seems to be that it cannot find the `game/code` folder.

@LrrrAc your issue seems to be caused by the API I use for game data (specifically the part that downloads background images). What is the EXACT name of the game this happens for. I need to manually check it against the API to see where the issue is coming from.

Also as a side note: you may or may not find it easier to communicate with me on Discord (using the repo is starting to become cluttered for this bug report). If you wish, you can also reach me here https://discord.gg/WYVnFEQ (it may also be faster, since I do not always have GitHub open)

**Comment by RedDuckss** [comment] 2017-04-13 01:40
@boonynator @davidevan84 please try this 3rd test build. https://www.dropbox.com/s/9kzcouy1qq751c3/CemuManager-win32-ia32%20DEV%203.zip?dl=0

It has already been confirmed to fix the issue that @LrrrAc was having.

**Comment by davidevan84** [comment] 2017-04-13 03:22
Ok so I think I figured out the issue. This might seem obvious cause it does seem consistent. I Just think the way the program is setup is if it notices anything outside of a game folder as normally structured it doesn't know how to just skip over that folder. It just errors out the entire program instead. I had some folders in my Wii U folder that arent games and I took those out completely and took out a couple games that seem to be throwing an issue and now its fine. You did something that fixed part of it though. Because on previous builds I created a folder and just put the game Paper Mario Splash in it and it still error'd out. Now testing that same game it does not error out with the most recent build of the Application.

**Comment by davidevan84** [comment] 2017-04-13 03:23
Also I know you just started this application and again probably obvious but at this point if I add a game after the initial start up that game doesnt show up. So there needs to be a refresh option of some sort. I assume you are aware that it doesnt show up after the initial scan just making sure just in case.

**Comment by RedDuckss** [comment] 2017-04-13 03:39
I'm a bit confused on what you're trying to say in your first reply. You start off by making it sound as if the issue is still occurring, but the way you ended the statement makes it sound as if the issue is resolved.

So just to clarify: is the issue still happening using the latest build I provided here?

The build I most recently provided does a full scan of each of the folders in the directory, checking for not only the 3 game sub-folders but also the rom file and meta file. So that issue should not be occurring. In fact, I am unsure as to why it was even occurring for you in the first place. In my games folder, I have a completely empty folder, and in my BOTW game folder I have an `updates` subfolder along with the other 3 subfolders, and I have not had any errors while scanning on any build.

Also yes we are aware of the fact that games do not refresh when you add/remove games from the game folder. I have been going over several methods of doing this since day-one, trying to find the best method for this specific program. I plan to release an option to refresh the games folder in the next official build, along with options to change the game/Cemu folder.

**Comment by davidevan84** [comment] 2017-04-13 03:43
Ok so what im saying is there are TWO different issues I was really having. One was if theres any folders within the Main folder it errors out. It doesnt know how to just skip a folder that isnt a game. That issue hasnt been resolved, the Second error was certain games in a folder by itself would also error out that issue seems to be resolved.

**Comment by RedDuckss** [comment] 2017-04-13 03:49
The issue with it "not skipping" folders that aren't games is still puzzling to me. If you check the source for the latest build (which is found in `app.js` of the dev branch), you can see that it looks for a `content`, `code` and `meta` folder to all be present in the game folder. If any of them are not there, it returns false which skips the folder. If they are there, it then checks for `meta/meta.xml` and the rom file in `code/NAME.rpx` (it isn't hard-coded for `NAME`, it checks for a file with the `.rpx` extension). If one of them does not exist, it again returns false and skips the folder. It will only return true if it meets all the criteria for a valid game. Those are also the _only_ two files being used by the program, which is why it only checks for those two.

**Comment by davidevan84** [comment] 2017-04-13 03:56
Ya thats weird cause im pretty sure that is what its doing. I have a Folder just called Cemu Files. I use it strictly for storing shadercache game saves etc. On one of the errors it straight up says that folder is whats holding it up.

**Comment by davidevan84** [comment] 2017-04-13 03:58
![8b3715f6-1fb5-11e7-8a8f-4260ec160308](https://cloud.githubusercontent.com/assets/22285162/24989631/93979bf8-1fd3-11e7-9b28-989831357918.png)

**Comment by davidevan84** [comment] 2017-04-13 03:59
Actually I have the Mario DLC within that folder since its just the DLC and not the full game could that be causing an issue?

**Comment by davidevan84** [comment] 2017-04-13 04:01
Nope Nvm I took out the Cemu Folder and now the error shows up on a different solder that I just put the saves in for testing purposes and same error.

**Comment by RedDuckss** [comment] 2017-04-13 04:09
It honestly makes no sense.

This is the logic going on in the back-end:

When you select a folder, it returns the folder path. I then take the folder path and grab all the directories in it, using `var gameDirs = getDirectories(game_folder_path[0]);`. The `getDirectories` function only returns this `return fs.readdirSync(src).filter(file => fs.statSync(path.join(src, file)).isDirectory());`, which returns an array of ONLY folders (no files).

I then loop through them all, passing each through a `isGame` function:
```
if (isGame(gamePath)) { // verifies that it's a game
/* Logic for if it is a game */
}
```
The `isGame` function is running:
```
function isGame(folder) { // Checks if it's a game or not
	var subDirs = getDirectories(folder);
	if (subDirs === undefined || subDirs.length == 0) {
	    return false;
	}
	if (subDirs["code"] === null || subDirs["content"] === null || subDirs["meta"] === null) {
		return false;
	}

	var codeFile = fs.readdirSync(folder+"\\code").filter(/./.test, /\.rpx$/i);

	if (codeFile === undefined || codeFile.length == 0) {
		return false;
	}

	if (fs.existsSync(folder+"\\meta\\meta.xml") === null) {
		return false;
	}

	return true;
}
```
Which first searches for the 3 folders `code`, `content` and `meta`. As you can see, if even one of them does not exist, it returns false which skips the folder. Then it checks the `code` and `meta` folders for the required files. If one of them does not exist, it returns false which skips the folder.

The line throwing the error is line 107. This line is `rom = files.filter(/./.test, /\.rpx$/i)[0];` which finds the rom file. The error being thrown says that the `code` folder _cannot_ be found.

However, to even make it to this line, it needs to pass the `isGame` function. And the only way to do that is if the code folder _does_ exist.

**Comment by davidevan84** [comment] 2017-04-13 04:14
On your page introducing the program you have some short video or gif application. What are you using? I can try to make a similiar video animated gif to show you what im doing and show you whats in the folder that is throwing flags so you see what I am saying.

**Comment by RedDuckss** [comment] 2017-04-13 04:15
As a test, I have a folder in my games folder named `Outlier (not a real game)` which is completely empty. This folder is being skipped by the program, with no errors. Also in my Zelda BOTW folder, I have a 4th sub-folder called `updates` which contains several GB of arbitrary data. It also throws no error with that game.

**Comment by RedDuckss** [comment] 2017-04-13 04:15
The program being used there is called ShareX, with the gif addon

**Comment by davidevan84** [comment] 2017-04-13 04:26
Have you tried putting a folder that isnt empty? I mean I dont know much about programming but comparing a Empty folder where the program isnt going to see anything vs a folder that isnt empty at all. Is that really going to be a fair comparison?

**Comment by RedDuckss** [comment] 2017-04-13 04:34
We're getting somewhere. In my initial testing, I did indeed fill the outlier folder with content as well as keeping it empty during some tests, depending on what I was doing. However thinking back on it, I don't believe I ever put any folders inside it, only files (like zips and such).

I was able to recreate your error by putting an empty folder inside the outlier. Now I have a basis for tracking down the bug.

**Comment by davidevan84** [comment] 2017-04-13 04:38
Awesome. Ya the Saves folder has the Mlc01 folder from cemu just copied into it since that has saves etc. So Ill try taking out its sub folders and just leave an empty save folder and I bet it will work.

**Comment by davidevan84** [comment] 2017-04-13 04:42
Yup thats totally what it is. Every folder that isnt a game folder that has a sub folder crashes it.  If it has sub folders but its within a game its fine.

**Comment by RedDuckss** [comment] 2017-04-13 04:50
I believe I've worked out why this bug is happening. Stupid me was reading the `subDirs` array backwards. I was reading the _values_ and seeing them as _keys_ (I blame this on how Node logs arrays with numerical indexes, it logs only the values which makes them look like keys). So in reality the `if (subDirs["code"] === null || subDirs["content"] === null || subDirs["meta"] === null)` was doing nothing. Changing it out with `if (Object.values(subDirs).indexOf('code') <= -1 || Object.values(subDirs).indexOf('content') <= -1 || Object.values(subDirs).indexOf('meta') <= -1)` seems to have fixed the issue.

Going to run a few more tests, then compile a build and send it your way for testing.

**Comment by boonynator** [comment] 2017-04-13 04:53
I'll check if the same or any other issues occur to me on the same or latest build you upload here, once I'm home.  Thanks for the hard work

**Comment by davidevan84** [comment] 2017-04-13 04:53
Ok cool. No worries man I have friends who are into coding and I know its so easy to make a mistake you gotta double check every little thing.  Just glad I could help.

**Comment by RedDuckss** [comment] 2017-04-13 05:02
https://www.dropbox.com/s/5zl8pauz3nk4ftj/CemuManager-win32-ia32%20DEV%204.zip?dl=0

Hopefully this one fixes everything.

**Comment by davidevan84** [comment] 2017-04-13 05:05
![newerror](https://cloud.githubusercontent.com/assets/22285162/24990918/e0fbb038-1fdc-11e7-8f36-8bee94a3b1d8.png)

**Comment by davidevan84** [comment] 2017-04-13 05:05
So first error is fixed now a new one lol.

**Comment by RedDuckss** [comment] 2017-04-13 05:09
Fix one bug and 3 more popup, as it goes.

That one seems to be related to a bug previously mentioned by someone else. Would you mind sending me a full list of the games you have? It'll be easier for me to track down which one is causing the error, and finding a patch for it, if I have a full list (It's related to the API not returning a specific value for the game, which throws an error)

**Comment by davidevan84** [comment] 2017-04-13 05:15
Shantae and the Pirates Curse
Star fox Zero
Yoshis Woolly World
Axiom Verge
Bayonetta
Captain Toad Treasure Tracker
Kirby and the Rainbow Curse
Mario Kart 8
Metroid Prime Trilogy
NES Remix
Super Mario Bros U
Paper Mario Color Splash
Pikmin 3
Shantae half Genie Hero
Shantae Risky Revenge 
Super Mario Maker
Super Meat boy
Zelda Skyward Sword
BOTW
Wind Waker
Tokyo Mirage Seassions FE
ZombiU
Shovel Knight
Twilight Princess
Xenoblade Chronicles X
Bayonetta 2
Donkey Kong Country Tropical Freeze
Super Mario 3D world

**Comment by RedDuckss** [comment] 2017-04-13 05:24
I just checked the specific line for where the bug is happening. It can't seem to find the number of players for the game. Added an extra check that set's it to `1` if it can't find a proper value. Compiling now.

**Comment by RedDuckss** [comment] 2017-04-13 05:42
https://www.dropbox.com/s/oxzt0k8c9zm9309/CemuManager-win32-ia32%20DEV%205.zip?dl=0

Let's hope this one doesn't mess up.

**Comment by davidevan84** [comment] 2017-04-13 05:45
Now Im getting two different Error messages back to back the last one I added that says 0 undefined and now this one too.  
![newest error](https://cloud.githubusercontent.com/assets/22285162/24991708/7f64d20e-1fe2-11e7-8c74-6b74b10b22f9.png)

**Comment by RedDuckss** [comment] 2017-04-13 05:53
The only reason an error would be thrown on that line is if the API returned absolutely no data for a game (which I forgot to check for).

Are any of your games non-English? That's the only thing I can think of as to why it wouldn't return any data.

**Comment by davidevan84** [comment] 2017-04-13 06:49
No all my games are in english some Europe and some USA but all English.

**Comment by RedDuckss** [comment] 2017-04-13 07:08
https://www.dropbox.com/s/r41daz5ykbq3mgq/CemuManager-win32-ia32%20DEV%206.zip?dl=0

This build now checks if the API returns no data. It will also log which games return no data.

**Comment by davidevan84** [comment] 2017-04-13 07:17
same two errors as before.

**Comment by RedDuckss** [comment] 2017-04-13 07:23
That shouldn't be possible...the error occurs here `result["Data"]["Game"][game_index]["id"]` where the `game_index` is (for some reason) undefined...that should only happen when `Game` has no indexes since `game_index` is `0` by default (so it's never really undefined). The only time `Game` would have no indexes is if no data was returned at all, however I added checks for that, and they work perfectly on my end...

**Comment by davidevan84** [comment] 2017-04-13 08:13
Ya idk whats going on. I just get the exact same errors.

**Comment by RedDuckss** [comment] 2017-04-13 08:13
Perfect timing. I just finished another build

**Comment by RedDuckss** [comment] 2017-04-13 08:14
Let's hope my 4am self was able to _finally_ fix this bug:
https://www.dropbox.com/s/ujtxg3ceazoq3ch/CemuManager-win32-ia32%20DEV%207.zip?dl=0

**Comment by davidevan84** [comment] 2017-04-13 08:18
Same errors as before but now a new one. Where the last error I sent says ID now theres a new one that says Images.

**Comment by RedDuckss** [comment] 2017-04-13 08:19
So the `id` error is now gone completely, and is replaced with `Images`? Good, making progress.

**Comment by RedDuckss** [comment] 2017-04-13 08:20
There are 3 lines which use the `Images` index. If you would, please post a screenshot of the error so I can find the exact line.

**Comment by davidevan84** [comment] 2017-04-13 08:21
Ok so checked again. It errors with 0 undefined which it did before. No more ID but now Images and one that says ratings also.

**Comment by RedDuckss** [comment] 2017-04-13 08:23
Screenshot of both errors please? I have a feeling I know where the issue is at for both but I need to be sure I'm targeting the correct lines.

**Comment by davidevan84** [comment] 2017-04-13 08:30
![errornew2](https://cloud.githubusercontent.com/assets/22285162/24996710/84389722-1ff9-11e7-9eeb-e6de9ec8aea8.png)

**Comment by davidevan84** [comment] 2017-04-13 08:30
![errornew](https://cloud.githubusercontent.com/assets/22285162/24996716/886ed0ae-1ff9-11e7-95d4-b88ce9558182.png)

**Comment by RedDuckss** [comment] 2017-04-13 09:33
https://www.dropbox.com/s/h87zn2v992rue3n/CemuManager-win32-ia32%20DEV%208.zip?dl=0
This build has additional checks as well as place-holder images for images which cannot be found.

**Comment by AppleT1ny** [comment] 2017-04-13 14:25
tested the latest devbuild
![bug](https://cloud.githubusercontent.com/assets/24819763/25009098/d432d74e-2065-11e7-8a06-9b988b8ca65e.PNG)

**Comment by RedDuckss** [comment] 2017-04-13 15:55
9th times a charm, I hope. I've now added in checks for every last bit of data

https://www.dropbox.com/s/6nyxchk6zrt0yud/CemuManager-win32-ia32%20DEV%209.zip?dl=0

**Comment by boonynator** [comment] 2017-04-13 16:03
Okay so the 9th build fixed all issues I had before, plus I didn't find any new ones yet.
Just out of curiosity, does the manager only scan direct subfolders of your Wii U Games directory for the "code", "content" and "meta" folder, or also goes deeper into like subfolders of subfolders, for example.

Main dir
│
└──── Random game folders...
└──── subfolder
│            │─── another subfolder
│            │         └──── Other game folders
│            │         │
.....

**Comment by RedDuckss** [comment] 2017-04-13 16:12
Oh my God that's a relief. Can finally close this issue. As for the game folder scanning, currently it only scans the direct children of the games folder. I haven't added any recursive searching, though I would love to add it some day.

**Comment by davidevan84** [comment] 2017-04-13 16:15
Still isnt fixed for me sorry. Same Images and Ratings Error I showed you prior still exists.

**Comment by RedDuckss** [comment] 2017-04-13 16:18
Are you sure you are using the latest (9th) dev build? The 9th dev build checks if each piece of data is undefined, and if it is it uses default data.

**Comment by davidevan84** [comment] 2017-04-13 16:19
Yup it says 9th DEV on the folder.

**Comment by davidevan84** [comment] 2017-04-13 16:20
the id and 0 undefined went away. so now its just rating which pops up twice and then image pops up once.

**Comment by davidevan84** [comment] 2017-04-13 16:26
I know its frustrating. Just trying to help as much as I can. No worries here ya go.

![error2](https://cloud.githubusercontent.com/assets/22285162/25014131/18807f48-203c-11e7-9cc2-2081a15a4751.png)

**Comment by davidevan84** [comment] 2017-04-13 16:27
![error3](https://cloud.githubusercontent.com/assets/22285162/25014137/1d41bfb0-203c-11e7-8d7f-4cd3e9b94705.png)

**Comment by davidevan84** [comment] 2017-04-13 16:28
The Rating error pops up twice but it looks 100% the same from what I can tell.

**Comment by RedDuckss** [comment] 2017-04-13 16:29
Yes I think I see where the issue comes from now. One moment.

**Comment by RedDuckss** [comment] 2017-04-13 16:41
Lucky number 10? Maybe? Hopefully?

https://www.dropbox.com/s/ud831iux4xfjo5l/CemuManager-win32-ia32%20DEV%2010.zip?dl=0

**Comment by davidevan84** [comment] 2017-04-13 16:51
Whew So errors are finally gone. Totally different issue now. You may be aware. but for whatever reason half my games arent showing up when it scans and a couple games showed up twice in the list.

**Comment by RedDuckss** [comment] 2017-04-13 16:55
I'm aware of some games not showing up. It has to do with the API, which I am debating scrapping in favor of a local file which stores game data. Since this issue is now resolved (as it was specifically about another issue), would you mind opening a separate issue for this new bug? It should also be noted that the `readme` now has criteria and steps for future bug reports.

**Comment by davidevan84** [comment] 2017-04-13 16:57
Ya I just have a quick question too. Cause I know this is new and its going to be awhile till its perfect. Some stuff I dont know if its considered a bug or just something that needs to be implemented. Like example you cant move the window around for the application if you scroll down at all through your games. If you scroll all the way back up you can move it again etc.

**Comment by davidevan84** [comment] 2017-04-13 16:58
But Yes I can create a new topic for each thing I find if you want.

**Comment by RedDuckss** [comment] 2017-04-13 17:00
Things like the window movement would be considered bugs, yes. If a feature currently implemented does not function as intended, then it's a bug and should be reported here. If it is a missing feature, or something not yet added, that would be a suggestion. Suggestions should be made in the Discord server, as to not clutter up the issue tracker. A link to the Discord is in the `readme`.

If several bugs seem to be connected or directly related (for example the bug with scanning directories here was directly linked to a bug where data was not being downloaded) then they should be in the same issue report. Only distinct bugs need their own report.

**Comment by davidevan84** [comment] 2017-04-13 17:02
Ok thats what I figured actually. That seems pretty straight forward and Logical. I created a couple tickets for what we just talked about. Let me know if you need anything else. I wont always be able to test everything but I dont mind playing Test Dummy when I can for ya.

**Comment by RedDuckss** [comment] 2017-04-13 17:04
Awesome. Thanks for all your help :)

**Closed by RedDuckss** 2017-04-13 17:04 UTC
Labels: bug
