### ISSUE TITLE
Games do not move when window is resized and there is room to the left

### ISSUE THREAD

**Issue by MrIlliteracy** [RedDuckss/CemuManager#10] opened 2017-04-11 00:02 UTC
![](http://i.imgur.com/uJzapi2.gif)

**Comment by RedDuckss** [comment] 2017-04-11 03:03
Fixed in v0.1.2

**Comment by MrIlliteracy** [comment] 2017-04-11 16:38
Not fixed for me?

**Comment by RedDuckss** [comment] 2017-04-11 16:43
Ensure you are using the latest copy of the repo and provide a screenshot of the error in the latest version, please. I cannot replicate this bug.

**Comment by MrIlliteracy** [comment] 2017-04-11 16:46
Its the same as the gif above, i know i was using the latest version (with a clean install) because i was developing on it

**Comment by RedDuckss** [comment] 2017-04-11 16:47
Will look in to this further. Could possibly be caused by differing screen resolutions and sizes, as I cannot replicate this issue on any build.

**Comment by MrIlliteracy** [comment] 2017-04-11 16:48
Yeah thats what I was thinking, my screen res is 1080p

**Comment by RedDuckss** [comment] 2017-04-11 16:48
I use a 4K LG TV. This is most likely the cause.

**Closed** 2017-04-11 23:10 UTC
Labels: bug
