### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by dem0z** [RedDuckss/CemuManager#18] opened 2017-04-18 19:39 UTC
this happens when i try to add the wii u games folder other than that the app starts fine.
http://imgur.com/95SA6hB

i am on windows 10 (creators update) with java updated.

Edit: this is caused by New Super Mario Bros U if it's in the folder it gets that error.

**Comment by RedDuckss** [comment] 2017-04-18 21:05
This seems to be related to issue #13, which has been solved. The fix has not yet been pushed to the dev branch, and a release with the fix has not been released. It will be released soon, within the week if all goes well. Please check the dev build posted in issue #13 and see if the issue still persists.

It should be noted that the issue is caused due to the format of the API I am using. I am currently in the process of making a custom API specifically for CemuManager that will better suit the programs needs, and remove all errors like this in the future. However it will take time to release, since I must manually write 3,113 pieces of data (1/3 of which is in Japanese)

**Comment by dem0z** [comment] 2017-04-18 21:09
Take your time no rush thanks for the quick reply and good luck :)

**Comment by RedDuckss** [comment] 2017-04-19 01:58
Have you confirmed that this error is fixed in the test build found on issue #13? The link to this issue is https://github.com/RedDuckss/CemuManager/issues/13, as well the link to the test build is https://www.dropbox.com/s/ud831iux4xfjo5l/CemuManager-win32-ia32%20DEV%2010.zip?dl=0

**Comment by dem0z** [comment] 2017-04-19 11:54
just tried it and working with no errors at all, thank you.

**Comment by RedDuckss** [comment] 2017-04-19 14:33
okay, thank you.

**Closed by RedDuckss** 2017-04-19 14:33 UTC
